# Generated by Django 5.0 on 2024-09-11 19:13

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('auth_user_app', '0001_initial'),
    ]

    operations = [
        migrations.AlterField(
            model_name='user',
            name='role',
            field=models.CharField(choices=[('admin', 'Administrador'), ('gestor', 'Gestor'), ('usuario', 'Usuario')], default='usuario', max_length=20),
        ),
    ]
