# Generated by Django 5.0 on 2024-09-19 14:45

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        ('facultad_app', '0001_initial'),
    ]

    operations = [
        migrations.CreateModel(
            name='Catedra',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('nombre_catedra', models.CharField(max_length=100)),
                ('fecha_inicio', models.DateField()),
                ('fecha_fin', models.DateField(blank=True, null=True)),
                ('facultad', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='facultad_app.facultad')),
            ],
        ),
        migrations.CreateModel(
            name='Doctorado',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('nombre_doctorado', models.CharField(max_length=100)),
                ('coordinador', models.CharField(max_length=100)),
                ('fecha_inicio', models.DateField()),
                ('fecha_fin', models.DateField(blank=True, null=True)),
                ('excelencia', models.BooleanField(default=False)),
                ('facultad', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='facultad_app.facultad')),
            ],
        ),
        migrations.CreateModel(
            name='Maestria',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('nombre_maestria', models.CharField(max_length=100)),
                ('coordinador', models.CharField(max_length=100)),
                ('fecha_inicio', models.DateField()),
                ('fecha_fin', models.DateField(blank=True, null=True)),
                ('excelencia', models.BooleanField(default=False)),
                ('facultad', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='facultad_app.facultad')),
            ],
        ),
    ]
