# Generated by Django 5.0 on 2024-09-19 14:45

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        ('facultad_app', '0001_initial'),
        ('sede_app', '0001_initial'),
    ]

    operations = [
        migrations.CreateModel(
            name='Cargo',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('nombre_cargo', models.CharField(max_length=100)),
                ('descripcion', models.TextField(blank=True, null=True)),
            ],
        ),
        migrations.CreateModel(
            name='Docente',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('nombre_docente', models.CharField(max_length=100)),
                ('apellido_docente', models.CharField(max_length=100)),
                ('ci', models.CharField(max_length=20)),
                ('telefono', models.CharField(blank=True, max_length=15, null=True)),
                ('correo', models.EmailField(blank=True, max_length=254, null=True)),
                ('fecha_alta', models.DateField()),
                ('fecha_baja', models.DateField(blank=True, null=True)),
                ('cargo', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, to='docente_app.cargo')),
            ],
        ),
        migrations.CreateModel(
            name='DocenteFacultad',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('area_facultad', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='facultad_app.areafacultad')),
                ('docente', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='docente_app.docente')),
            ],
            options={
                'unique_together': {('docente', 'area_facultad')},
            },
        ),
        migrations.CreateModel(
            name='DocenteSede',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('area_sede', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='sede_app.areasede')),
                ('docente', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='docente_app.docente')),
            ],
            options={
                'unique_together': {('docente', 'area_sede')},
            },
        ),
    ]
